### PR TITLE
add about go run in wsl

### PR DESCRIPTION
**Pull request by yktakaha4**
Thanks for a great library.

I am using Ebitengine with WSL2 and have encountered the same problem as the following Issue.
https://github.com/hajimehoshi/ebiten/issues/2643

If this is recommended, it should be explained in the official documentation.
Please let me know if there is a proper way to execute this or where to describe it.

### en

image

### ja

image

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks. Can you make the paragraphs in `<div data-tags="windows">` so that they are shown only for Windows?

**Comment by yktakaha4** [comment]
I wrapped the contents in `data-tags`.
However, this is the procedure for running the sample in a Linux environment inside Windows, so I thought the value `linux` would be better.

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Comment by hajimehoshi** [comment]
> However, this is the procedure for running the sample in a Linux environment inside Windows, so I thought the value linux would be better.

0c96f80a6fdeeed2ce9053551b135f14a1881b09

I fixed the tags to show the instruction for both OSes

**Pull request merged**
